# This workflow will validate Pull Requests as per Database Standards

name: DBCheckInPolicy
on:
  workflow_dispatch:
  pull_request:
    branches: 
      - development-22.2
      - development-23.1
    types: [opened, synchronize, reopened, edited]
              
jobs:
  analyze:
    name: DB Standard Checkin Policy
    runs-on: self-hosted
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: GitHubDbCheckinPolicy
      run: |
          E:\VNext\DbCheckInPolicy\DatabaseStandards\DatabaseStandards.exe ${{ github.event.number }} ${{ github.repository }} ${{ secrets.GITTOKEN }}         
