# This workflow will validate Pull Requests as per Database Standards

name: DBCheckInPolicy
on:
    pull_request:
              
jobs:
  analyze:
    name: DB Standard Checkin Policy
    runs-on: self-hosted
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: GitHubDbCheckinPolicy
      run: |
          E:\VNext\DbCheckInPolicy\DatabaseStandards\DatabaseStandards.exe ${{ github.event.number }} ${{ github.repository }} ${{ secrets.GITTOKEN }}         
